# Our github dependencies
# https://github.com/smartcontractkit/chainlink-brownie-contracts
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
  - OpenZeppelin/openzeppelin-contracts@4.4.2

# tell our compiler
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'

# Where to get our environment variable
dotenv: .env

networks:
  # default development network
  default: development
  development:
    # https://docs.chain.link/docs/vrf-contracts/
    # we default the same as rinkeby
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
  rinkeby:
    # https://docs.chain.link/docs/vrf-contracts/
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    # https://docs.chain.link/docs/link-token-contracts/
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
  mainnet-fork:
    # price feed from mainnet
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'

wallets:
  from_key: ${PRIVATE_KEY}
